#pragma once
/* XPM */
#include <lcom/lcf.h>
#include "../../colors.h"
#include <string.h>

xpm_row_t kll58[] = {
/* columns rows colors chars-per-pixel */
"58 58 3 1",
"  g #000000",
". g #000069",
"X g #FFFFFF",
/* pixels */
"..........................................................",
"..........................................................",
"..........................................................",
"..........................................................",
"..........................................................",
"............................  ............................",
"............................  ............................",
"............................  ............................",
".........................        .........................",
".........................        .........................",
"............................  ............................",
"............................  ............................",
"............................  ............................",
"............................  ............................",
"............................  ............................",
"..........................      ..........................",
".........................   XX   .........................",
".........................  XXXX  .........................",
"........................   XXXX   ........................",
"...........       ......  XXXXXX  ......       ...........",
".........           ....  XXXXXX  ....           .........",
".......    XXXXXXX    ..  XXXXXX  ..    XXXXXXX    .......",
"......   XXXXXXXXXXX      XXXXXX      XXXXXXXXXXX   ......",
".....   XXXXXXXXXXXXXX    XXXXXX    XXXXXXXXXXXXXX   .....",
".....  XXXXXXXXXXXXXXXX    XXXX    XXXXXXXXXXXXXXXX  .....",
"....   XXXXXXXXXXXXXXXXX   XXXX   XXXXXXXXXXXXXXXXX   ....",
"....  XXXXXXXXXXXXXXXXXXX   XX   XXXXXXXXXXXXXXXXXXX  ....",
"....  XXXXXXXXXXXXXXXXXXX   XX   XXXXXXXXXXXXXXXXXXX  ....",
"....  XXXXXXXXXXXXXXXXXXXX      XXXXXXXXXXXXXXXXXXXX  ....",
"....  XXXXXXXXXXXXXXXXXXXX      XXXXXXXXXXXXXXXXXXXX  ....",
"....  XXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXX  ....",
"....   XXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXX   ....",
".....  XXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXX   .....",
".....   XXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXX  ......",
"......   XXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXX   ......",
".......   XXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX   .......",
"........   XXXXXXXXXXX              XXXXXXXXXXX   ........",
".........   XXXXX                        XXXXX   .........",
"..........            XXXXXXXXXXXXXX            ..........",
"...........      XXXXXXXXXXXXXXXXXXXXXXXX      ...........",
"............  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  ............",
"............  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  ............",
"............  XXXXXXXX              XXXXXXXX  ............",
"............  XXX                        XXX  ............",
"............          XXXXXXXXXXXXXX          ............",
"............     XXXXXXXXXXXXXXXXXXXXXXXX     ............",
"............  XXXXXXXXX            XXXXXXXXX  ............",
"............  XXXX                      XXXX  ............",
"............  X        XXXXXXXXXXXX        X  ............",
"............      XXXXXXXXXXXXXXXXXXXXXX      ............",
"............      XXXXXXXXXXXXXXXXXXXXXX      ............",
"...............        XXXXXXXXXXXX        ...............",
"..................                      ..................",
".......................            .......................",
"..........................................................",
"..........................................................",
"..........................................................",
".........................................................."
};
