#pragma once
/* XPM */
#include <lcom/lcf.h>
#include "../../colors.h"
#include <string.h>


xpm_row_t const kll80[] = {
/* columns rows colors chars-per-pixel */
"80 80 3",
"  0",
". 255",
"X 63", 
/* pixels */
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
".......................................  .......................................",
".......................................  .......................................",
".......................................  .......................................",
".......................................  .......................................",
"...................................          ...................................",
"...................................          ...................................",
".......................................  .......................................",
".......................................  .......................................",
".......................................  .......................................",
".......................................  .......................................",
".......................................  .......................................",
".......................................  .......................................",
".......................................  .......................................",
"......................................    ......................................",
"....................................        ....................................",
"...................................   XXXX   ...................................",
"..................................   XXXXXX   ..................................",
"..................................  XXXXXXXX  ..................................",
".................................   XXXXXXXX   .................................",
".................................  XXXXXXXXXX  .................................",
"................         ........  XXXXXXXXXX  ........         ................",
".............               .....  XXXXXXXXXX  .....               .............",
"............    XXXXXXXXX     ...  XXXXXXXXXX  ...     XXXXXXXXX    ............",
"..........    XXXXXXXXXXXXXX   ..  XXXXXXXXXX  ..   XXXXXXXXXXXXXX    ..........",
".........   XXXXXXXXXXXXXXXXX      XXXXXXXXXX      XXXXXXXXXXXXXXXXX   .........",
"........   XXXXXXXXXXXXXXXXXXXX     XXXXXXXX     XXXXXXXXXXXXXXXXXXXX   ........",
"........  XXXXXXXXXXXXXXXXXXXXXX    XXXXXXXX    XXXXXXXXXXXXXXXXXXXXXX  ........",
".......   XXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXX   .......",
".......  XXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXX  .......",
"......   XXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXX   ......",
"......  XXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXX  ......",
"......  XXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXX  ......",
"......  XXXXXXXXXXXXXXXXXXXXXXXXXXXX   XX   XXXXXXXXXXXXXXXXXXXXXXXXXXXX  ......",
"......  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  ......",
"......  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  ......",
"......   XXXXXXXXXXXXXXXXXXXXXXXXXXXX      XXXXXXXXXXXXXXXXXXXXXXXXXXXX   ......",
".......  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  .......",
".......   XXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXX   .......",
"........  XXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXX  ........",
"........   XXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXX   ........",
".........   XXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXX   .........",
"..........   XXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXX   ..........",
"...........   XXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXX   ...........",
"............   XXXXXXXXXXXXXXXXX                XXXXXXXXXXXXXXXXX   ............",
".............   XXXXXXXXXX                            XXXXXXXXXX   .............",
"..............   XXXXX          XXXXXXXXXXXXXXXX          XXXXX   ..............",
"...............   X       XXXXXXXXXXXXXXXXXXXXXXXXXXXX       X   ...............",
"................      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      ................",
".................  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  .................",
".................  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  .................",
".................  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  .................",
".................  XXXXXXXXXXXXXX              XXXXXXXXXXXXXX  .................",
".................  XXXXXXXX                          XXXXXXXX  .................",
".................  XXXX          XXXXXXXXXXXXXX          XXXX  .................",
".................  X       XXXXXXXXXXXXXXXXXXXXXXXXXX       X  .................",
".................      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      .................",
".................   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   .................",
".................   XXXXXXXXXXXXX              XXXXXXXXXXXXXX  .................",
"..................  XXXXXXX                          XXXXXXX   .................",
"..................  XXXX         XXXXXXXXXXXXXX         XXXX  ..................",
"..................  X      XXXXXXXXXXXXXXXXXXXXXXXXXX      X  ..................",
"..................      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      ..................",
"..................     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     ..................",
"....................       XXXXXXXXXXXXXXXXXXXXXXXXXX       ....................",
".......................         XXXXXXXXXXXXXXXX         .......................",
"...........................                          ...........................",
"................................                ................................",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................"
};
