#pragma once
/* XPM */
#include <lcom/lcf.h>
#include "../../colors.h"
#include <string.h>

xpm_row_t nll58[] = {
/* columns rows colors chars-per-pixel */
"58 58 3 1",
"  g #000000",
". g #000069",
"X g #FFFFFF",
/* pixels */
"..........................................................",
"..........................................................",
"..........................................................",
"..........................................................",
"..........................................................",
"............... .........  ...............................",
"..............   .......    ..............................",
"..............     .....    ..............................",
"...............     ...      .............................",
"...............  X   .   XX  .............................",
"...............  XX     XXX      .........................",
"...............  XXX    XXX         ......................",
"...............  XX     XXX  XXX      ....................",
"..............   X   XXXXXXX XXXXX      ..................",
".............   XX XXXXXXXXXXXXXXXXX     .................",
"............   XXXXXXXXXXXXXXXXXXXXXXX    ................",
"............  XXXXXXXXXXXXXXXXXXXXXXXXX    ...............",
"...........   XX    XXXXXXXXXXXXXXXXXXXX    ..............",
"...........  XX    XXXXXXXXXXXXXXXXXXXXXX    .............",
"...........  XX    XXXXXXXXXXXXXXXXXXXXXX     ............",
"...........  XX   XXXXXXXXXXXXXXXXXXXXXXXX    ............",
"..........   XX XXXXXXXXXXXXXX  XXXXXXXXXXX    ...........",
"..........  XXXXXXXXXXXXXXXXXX  XXXXXXXXXXX    ...........",
"..........  XXXXXXXXXXXXXXXXXX  XXXXXXXXXXXX    ..........",
".........   XXXXXXXXXXXXXXXXXX  XXXXXXXXXXXX    ..........",
".........  XXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXX    .........",
"........   XXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXX    .........",
".......   XXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXX    .........",
"......   XXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXX    ........",
"......  XXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXX    ........",
".....   XXXXXXXXXXXXXXXXX      XXXXXXXXXXXXXXX    ........",
".....  XXXXXXXXXXXXXXXX    ..  XXXXXXXXXXXXXXXX    .......",
"....   X  XXXXXXXXXXX    ....  XXXXXXXXXXXXXXXX    .......",
"....  X   XXXXXXXXX    .....   XXXXXXXXXXXXXXXX    .......",
"....  X   XXXXXXXX   .......  XXXXXXXXXXXXXXXXX    .......",
"....  X  XXXXXXXX   .......   XXXXXXXXXXXXXXXXX     ......",
"....  XXXXXX  XX   ........  XXXXXXXXXXXXXXXXXXX    ......",
"....  XXXXX   X   ........   XXXXXXXXXXXXXXXXXXX    ......",
"....   XXX       ........   XXXXXXXXXXXXXXXXXXXX    ......",
".....        X  ........   XXXXXXXXXXXXXXXXXXXXX    ......",
".......         .......   XXXXXXXXXXXXXXXXXXXXXX    ......",
"............   .......   XXXXXXXXXXXXXXXXXXXXXXX     .....",
".....................   XXXXXXXXXXXXXXXXXXXXXXXX     .....",
"....................   XXXXXXXXXXXXXXXXXXXXXXXXXX    .....",
"....................  XXXXXXXXXXXXXXXXXXXXXXXXXXX    .....",
"...................   XXXXXXXXXXXXXXXXXXXXXXXXXXX    .....",
"..................   XXXXXXXXXXXXXXXXXXXXXXXXXXXX    .....",
"..................  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .....",
".................   XXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .....",
".................  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .....",
".................  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .....",
".................                                    .....",
".................                                    .....",
"..........................................................",
"..........................................................",
"..........................................................",
"..........................................................",
".........................................................."
};
