#pragma once
/* XPM */
#include <lcom/lcf.h>
#include "../../colors.h"
#include <string.h>


xpm_row_t const nll80[] = {
/* columns rows colors chars-per-pixel */
"80 80 3",
"  0",
". 255",
"X 63", 
/* pixels */
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
"......................  ............  ..........................................",
"......................   ..........    .........................................",
"......................    .........     ........................................",
"......................      ......   X  ........................................",
"......................  XX   .....  XX   .......................................",
"......................  XXX   ...   XXX  .......................................",
"......................  XXXX   ..  XXXX  .......................................",
"......................  XXXXX      XXXX        .................................",
"......................   XXXX     XXXXX           ..............................",
".......................  XXX   X  XXXXXX  XXXX      ............................",
"......................   XX   XXXXXXXXXX  XXXXXXX     ..........................",
".....................   XX   XXXXXXXXXXXXXXXXXXXXXX     ........................",
"....................   XXX  XXXXXXXXXXXXXXXXXXXXXXXX     .......................",
"...................   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ......................",
"...................  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .....................",
"..................   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ....................",
"..................  XXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXX    ...................",
"..................  XXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     ..................",
".................   XXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     .................",
".................  XXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .................",
".................  XXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ................",
".................  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ................",
"................   XXX XXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXX    ...............",
"................  XXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXX    ...............",
"................  XXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXX    ..............",
"...............   XXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXX    ..............",
"...............  XXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX    .............",
"..............   XXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXX    .............",
"..............  XXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXX     ............",
".............   XXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXX    ............",
"............   XXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXXXXXX    ............",
"............  XXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXX     ...........",
"...........   XXXXXXXXXXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXX    ...........",
"...........  XXXXXXXXXXXXXXXXXXXXXXXXX   .  XXXXXXXXXXXXXXXXXXXXX    ...........",
"..........   XXXXXXXXXXXXXXXXXXXXXXX    ..  XXXXXXXXXXXXXXXXXXXXX     ..........",
".........   XXXXXXXXXXXXXXXXXXXXXX    ....  XXXXXXXXXXXXXXXXXXXXXX    ..........",
".........  XXXXXXXXXXXXXXXXXXXXX    ......  XXXXXXXXXXXXXXXXXXXXXX    ..........",
".........  XX  XXXXXXXXXXXXXXX    ........  XXXXXXXXXXXXXXXXXXXXXX    ..........",
"........   X   XXXXXXXXXXXXXX   .........   XXXXXXXXXXXXXXXXXXXXXX     .........",
"........  XX   XXXXXXXXXXXX    ..........  XXXXXXXXXXXXXXXXXXXXXXXX    .........",
"........  XX   XXXXXXXXXXX   ...........   XXXXXXXXXXXXXXXXXXXXXXXX    .........",
"........  XX  XXXXXXXXXXX   ............  XXXXXXXXXXXXXXXXXXXXXXXXX    .........",
"........  XXXXXXXX  XXXX   ............   XXXXXXXXXXXXXXXXXXXXXXXXX    .........",
"........  XXXXXXXX  XXX   ............   XXXXXXXXXXXXXXXXXXXXXXXXXX     ........",
"........  XXXXXXX   XX   .............  XXXXXXXXXXXXXXXXXXXXXXXXXXXX    ........",
"........   XXXXXX  XX   .............   XXXXXXXXXXXXXXXXXXXXXXXXXXXX    ........",
".........   XXXX   X   .............   XXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ........",
"..........        XX  .............   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ........",
"............          ............   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ........",
".................   .............   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ........",
"................................   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ........",
"...............................   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     .......",
"..............................   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     .......",
".............................   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .......",
".............................  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .......",
"............................   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .......",
"...........................   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .......",
"...........................  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .......",
"..........................   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .......",
"..........................  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .......",
".........................   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .......",
".........................  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .......",
".........................  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    .......",
".........................                                                .......",
".........................                                                .......",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................",
"................................................................................"
};
